[project]
name = "prototyping"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckduckgo-search>=8.1.1",
    "googlesearch-python>=1.3.0",
    "playwright>=1.58.0",
    "playwright-stealth>=2.0.1",
]
